---
abstract: 'List of unicode blocks.'
author:
  - 'Michal Špaček <skim@cpan.org>'
build_requires:
  English: 0
  ExtUtils::MakeMaker: 6.36
  File::Object: 0.06
  Test::More: 0
  Test::NoWarnings: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Unicode-Block-List
no_index:
  directory:
    - inc
    - t
requires:
  Class::Utils: 0.02
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Unicode-Block-List
  homepage: https://github.com/tupinek/Unicode-Block-List
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/tupinek/Unicode-Block-List
version: 0.01
